name: verify-local-formula
run-name: Verify local Formula

on:
  push:
    branches-ignore: [ main ]
    paths: [ 'Formula/git-team.rb', '.github/workflows/*' ]
  pull_request:
    paths: [ 'Formula/git-team.rb', '.github/workflows/*' ]
  workflow_dispatch:

jobs:
  verify-local-formula:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    env:
      HOMEBREW_DEVELOPER: true
    steps:
      - uses: Homebrew/actions/setup-homebrew@75ea84e0c056f44fbc237368be867593cd459107 # master
      - run: brew install bubblewrap
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: brew install --verbose ./Formula/git-team.rb
      - run: brew audit git-team --strict
      - run: brew test git-team
      - run: git-team --version
