---
name: Verify black box style

# TODO: run only when Formula changed
on:
  push:
    branches:
      - master

jobs:
  verify-formula:
    # TODO: also run this on ubuntu using linuxbrew
    runs-on: macos-latest
    strategy:
      matrix:
        formula_version: ["", "--HEAD"]
    steps:
      - run: |
          sudo chown -R $(whoami) $(brew --prefix)/*
          sudo rm -rf /usr/local/opt/go@1.17
          sudo rm /usr/local/bin/go
          sudo rm /usr/local/bin/gofmt
      - run: brew tap hekmekk/git-team
      - run: brew install git-team ${{ matrix.formula_version }} --verbose
      # - run: brew audit git-team --strict
      - run: brew test git-team
      - run: git-team --version
